python ConvertWorld_ver2.py train/Bag Gra
python ConvertWorld_ver2.py train/Hips Gra
python ConvertWorld_ver2.py train/Torso Gra
python ConvertWorld_ver2.py train/Hand Gra
python ConvertWorld_ver2.py validation/Bag Gra
python ConvertWorld_ver2.py validation/Hips Gra
python ConvertWorld_ver2.py validation/Torso Gra
python ConvertWorld_ver2.py validation/Hand Gra
python ConvertWorld_ver2.py test Gra
python ConvertWorld_ver3.py train/Bag Gra
python ConvertWorld_ver3.py train/Hips Gra
python ConvertWorld_ver3.py train/Torso Gra
python ConvertWorld_ver3.py train/Hand Gra
python ConvertWorld_ver3.py validation/Bag Gra
python ConvertWorld_ver3.py validation/Hips Gra
python ConvertWorld_ver3.py validation/Torso Gra
python ConvertWorld_ver3.py validation/Hand Gra
python ConvertWorld_ver3.py test Gra