python ConvertWorld_ver3.py train/Bag
python ConvertWorld_ver3.py train/Hips
python ConvertWorld_ver3.py train/Torso
python ConvertWorld_ver3.py train/Hand
python ConvertWorld_ver3.py validation/Bag
python ConvertWorld_ver3.py validation/Hips
python ConvertWorld_ver3.py validation/Torso
python ConvertWorld_ver3.py validation/Hand
python ConvertWorld_ver3.py test