python ConvertWorld_ver2.py train/Bag Gyr
python ConvertWorld_ver2.py train/Hips Gyr
python ConvertWorld_ver2.py train/Torso Gyr
python ConvertWorld_ver2.py train/Hand Gyr
python ConvertWorld_ver2.py validation/Bag Gyr
python ConvertWorld_ver2.py validation/Hips Gyr
python ConvertWorld_ver2.py validation/Torso Gyr
python ConvertWorld_ver2.py validation/Hand Gyr
python ConvertWorld_ver2.py test Gyr
python ConvertWorld_ver3.py train/Bag Gyr
python ConvertWorld_ver3.py train/Hips Gyr
python ConvertWorld_ver3.py train/Torso Gyr
python ConvertWorld_ver3.py train/Hand Gyr
python ConvertWorld_ver3.py validation/Bag Gyr
python ConvertWorld_ver3.py validation/Hips Gyr
python ConvertWorld_ver3.py validation/Torso Gyr
python ConvertWorld_ver3.py validation/Hand Gyr
python ConvertWorld_ver3.py test Gyr